"""update the size og=f the image in models

Revision ID: 906580e5fb4c
Revises: 01ff1229fc5a
Create Date: 2024-04-23 23:23:05.719841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906580e5fb4c'
down_revision = '01ff1229fc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
